create table public.vk
(
    service_id   integer generated by default as identity
        constraint vk_pk
            primary key,
    service_name varchar not null,
    login        varchar not null,
    password     varchar not null,
    id_tg        integer
);

